vim.g.mapleader = " "

require 'mappings.barbar'
require 'mappings.fterm'
require 'mappings.general'
require 'mappings.hlslens'
require 'mappings.lsp'
require 'mappings.operator_pending'
require 'mappings.telescope'
require 'mappings.zenmode'

require 'mappings.editor.fold'
require 'mappings.editor.harpoon'
require 'mappings.editor.neoformat'
require 'mappings.editor.nrrwrgn'
require 'mappings.editor.nvimtree'
require 'mappings.editor.pacakage_info'
require 'mappings.editor.quickfix'
require 'mappings.editor.sneak'
require 'mappings.editor.speller'
require 'mappings.editor.todo'
require 'mappings.editor.trouble'
require 'mappings.editor.wordmotion'

require 'mappings.languages.jaq'
require 'mappings.languages.rails'
require 'mappings.languages.spector'
require 'mappings.languages.test'
require 'mappings.languages.vista'

require 'mappings.term.vimux'

require 'mappings.devops.aws'
require 'mappings.devops.network'
require 'mappings.devops.dadbod'
