vim.g.mapleader = " "

require("mappings.anzu")
require("mappings.buffer")
require("mappings.compe")
require("mappings.dashboard")
require("mappings.fterm")
require("mappings.general")
require("mappings.git")
require("mappings.lsp")
require("mappings.mundo")
require("mappings.rest")
require("mappings.telescope")
require("mappings.tree")
require("mappings.truezen")

require("mappings.editor.block")
require("mappings.editor.commenter")
require("mappings.editor.fold")
require("mappings.editor.markdown")
require("mappings.editor.nrrwrgn")
require("mappings.editor.prettier")
require("mappings.editor.sneak")
require("mappings.editor.trouble")
require("mappings.editor.wordmotion")

require("mappings.languages.rails")
