alias gm='git merge'
alias gs='git status'
alias gst='git stash'
alias gp='git push'
alias gpf='git push --force-with-lease'
alias gl='git pull'
alias gpo='git pull origin'
alias gco='git checkout'
alias gci='git commit'
alias grs='git reset --soft'
alias grh='git reset --hard'
alias gc='git remote prune origin'
alias gbda='git branch --no-color --merged | command grep -vE "^(\+|\*|\s*(master|develop|dev)\s*$argv)" | command xargs -n 1 git branch -d'
alias gfa='git fetch --all --prune'

alias ghcs='gh copilot suggest'
alias ghce='gh copilot explain'

alias yo='git add -A && git commit -m "$(curl -s https://whatthecommit.com/index.txt)"'
