vim.keymap.set('n', '<leader>gb', ':Telescope git_branches<CR>')
vim.keymap.set('n', '<leader>gc', ':Telescope git_commits<CR>')
vim.keymap.set('n', '<leader>gS', ':Telescope git_stash<CR>')
vim.keymap.set('n', ',gw', ':Telescope git_worktree<CR>')
vim.keymap.set('n', ',gc', ":lua require('telescope').extensions.git_worktree.create_git_worktree()<CR>")
vim.keymap.set('n', '<leader>gl', ':Git log<CR>')
vim.keymap.set('n', '<leader>gs', ':Telescope git_status<CR>')
