require 'config/lsp/servers/elixir'
require 'config/lsp/servers/golang'
require 'config/lsp/servers/html'
require 'config/lsp/servers/json'
require 'config/lsp/servers/ltex'
require 'config/lsp/servers/lua'
require 'config/lsp/servers/python'
require 'config/lsp/servers/ruby'
require 'config/lsp/servers/rust'
require 'config/lsp/servers/spell'
require 'config/lsp/servers/terraform'
require 'config/lsp/servers/typescript'
require 'config/lsp/servers/yamlls'
require 'config/lsp/servers/zig'

-- require 'config/lsp/servers/csharp'
-- require 'config/lsp/servers/gleam'
-- require 'config/lsp/servers/htmx'
-- require 'config/lsp/servers/kotlin'
-- require 'config/lsp/servers/nix'
-- require 'config/lsp/servers/ocaml'
-- require 'config/lsp/servers/smithy'
-- require 'config/lsp/servers/svelte'
-- require "config/lsp/bash"
-- require "config/lsp/css"
-- require "config/lsp/sql"
-- require 'config/lsp/deno'
