require("config.colors").init()

require "config.cores.bqf"
require "config.cores.gh"
require "config.cores.git"
require "config.cores.neorg"
require "config.cores.sneak"
require "config.cores.statusline"
require "config.cores.tabnine"
require "config.cores.tree"

require "config.libs.comment"
require "config.libs.cyclist"
require "config.libs.flutter_tool"
require "config.libs.fterm"
require "config.libs.git_conflict"
require "config.libs.git_worktree"
require "config.libs.indent_blankline"
require "config.libs.jaq"
require "config.libs.neoscroll"
require "config.libs.notify"
require "config.libs.nrrwrgn"
require "config.libs.preview_markdown"
require "config.libs.tint"
require "config.libs.todo"
require "config.libs.ufo"
require "config.libs.vim-test"
require "config.libs.vista"

require "config.whichkey"
