require "config.libs.alpha"
require "config.libs.comment"
require "config.libs.copilot"
require "config.libs.git_conflict"
require "config.libs.notify"
require "config.libs.oil"
require "config.libs.silicon"
require "config.libs.vim_test"
require "config.libs.vista"

-- require "config.cores.dap"
require "config.cores.git"
require "config.cores.statusline"
require "config.cores.telescope"
require "config.cores.tree"
