require("config.colors").init()

require "config.cores.navic"

require "config.cores.bqf"
require "config.cores.diagnostic"
require "config.cores.git"
require "config.cores.heirline"
require "config.cores.org"
require "config.cores.sneak"
require "config.cores.tree"

require "config.libs.comment"
require "config.libs.cyclist"
require "config.libs.flutter_tool"
require "config.libs.fterm"
require "config.libs.git_conflict"
require "config.libs.git_worktree"
require "config.libs.indent_blankline"
require "config.libs.neo-test"
require "config.libs.notify"
require "config.libs.nrrwrgn"
require "config.libs.preview_markdown"
require "config.libs.todo"
require "config.libs.ufo"
require "config.libs.vista"
require "config.libs.zenmode"
