#!/usr/bin/env bash

#+--- Bars General Config ---+
tmux set -g status-position bottom  # macOS / darwin style
tmux set -g status-left-length "200"
tmux set -g status-bg "#1E1E1E"
tmux set-option -g status-justify left

#+--- Bars LEFT ---+
tmux set -g status-left "#[fg=#15161e,bg=#d38aea,bold] #S #[fg=#2b97fa,bg=default,nobold,noitalics,nounderscore]"

#+--- Windows ---+
# Focus
tmux set -g window-status-current-format "#[fg=#98c379]  #[fg=#98c379]#I #[hnobold,nodim]#W"
# Unfocused
tmux set -g window-status-format "#[fg=#6f737b,bg=default,none,dim]  #I #W#[fg=yellow,blink]"

#+--- Bars RIGHT ---+
tmux set -g status-right "#[fg=gray]#{pomodoro_status} "
tmux set -ag status-right "#[fg=#50C16E] PIA: #{pia_status} #{pia_region}"
tmux set -ag status-right "#[fg=#ffff00] #(tmux list-panes | wc -l | tr -d ' ') panes"
