#!/usr/bin/env bash

#+--- Bars General Config ---+
tmux set -g status-position top  # macOS / darwin style
tmux set -g status-left-length "200"
tmux set -g status-bg "#0F0F0F"
tmux set-option -g status-justify left

#+--- Bars LEFT ---+
tmux set -g status-left "#[fg=#60FF60] #S #[fg=#2b97fa,bg=default,nobold,noitalics,nounderscore]"

#+--- Windows ---j
# Focus
tmux set -g window-status-current-format " #[fg=#E2E2E2]#I:#[hnobold,nodim]#{b:pane_current_path}"
# Unfocused
tmux set -g window-status-format "#[fg=#4F4F4F] #I:#{b:pane_current_path}#[fg=yellow,blink]"

#+--- Bars RIGHT ---+
tmux set -g status-right "#[fg=gray]#{pomodoro_status} "
tmux set -ag status-right "#[fg=#ffff00,bold] #(tmux list-panes | wc -l | tr -d ' ') panes"
