[[session]]
name = "LX-CONFIG"
path = "~/.dotfiles"

[[session]]
name = "LX-RESEARCH"
path = "~/LX14/projects/research"

[[session]]
name = "RegAsk"
path = "~/LX14/repository/github.com/regask"

[[session]]
name = "LX-PERSONAL"
path = "~/LX14/repository/github.com/louishuyng"

[[session]]
name = "gojem"
path = "~/LX14/repository/github.com/gojem"

[[session]]
name = "omniyat"
path = "~/LX14/repository/github.com/omniyat"
