# Personal

[[session]]
name = "LX-CONFIG"
path = "~/.dotfiles"

[[session]]
name = "LX-RESEARCH"
path = "~/LX14/projects/research"

[[session]]
name = "LX-PERSONAL"
path = "~/LX14/repository/github.com/louishuyng"

# Projects

[[session]]
name = "RegAsk"
path = "~/LX14/repository/github.com/regask"

[[session]]
name = "Gojem"
path = "~/LX14/repository/github.com/gojem"

[[session]]
name = "Omniyat"
path = "~/LX14/repository/github.com/omniyat"
