require 'mappings.editor.draft_buff'
require 'mappings.editor.buffer'
require 'mappings.editor.general'
require 'mappings.editor.telescope'
require 'mappings.editor.tree'
require 'mappings.editor.trouble'
