return {
  diagnostics = {
    Error = ' ',
    Warn = ' ',
    Hint = ' ',
    Info = ' ',
  },
  git = {
    added = '󰐕 ',
    modified = '󰏫 ',
    removed = '󰍴 ',
    renamed = '󰁕 ',
    untracked = '󰋗 ',
    ignored = '󰈉 ',
    unstaged = '󰄱 ',
    staged = '󰄵 ',
    conflict = '󰞇 ',
  },
  debug = {
    Breakpoint = '',
    BreakpointCondition = '',
    DebugLogPoint = '',
    Stopped = '',
    BreakpointRejected = '',
  },
  kinds = {
    Array = ' ',
    Boolean = '󰨙 ',
    Class = ' ',
    Codeium = '󰘦 ',
    Color = ' ',
    Control = ' ',
    Collapsed = ' ',
    Constant = '󰏿 ',
    Constructor = ' ',
    Copilot = ' ',
    Enum = ' ',
    EnumMember = ' ',
    Event = ' ',
    Field = ' ',
    File = ' ',
    Folder = ' ',
    Function = '󰊕 ',
    Interface = ' ',
    Key = ' ',
    Keyword = '󰌋 ',
    Method = ' ',
    Module = ' ',
    Namespace = '󰦮 ',
    Null = '󰟢 ',
    Number = '󰎠 ',
    Object = ' ',
    Operator = ' ',
    Package = ' ',
    Property = ' ',
    Reference = ' ',
    Snippet = ' ',
    String = ' ',
    Struct = '󰆼 ',
    Supermaven = ' ',
    TabNine = '󰏚 ',
    Text = ' ',
    TypeParameter = ' ',
    Unit = ' ',
    Value = '󰎠 ',
    Variable = ' ',
  },
}
