return {
  diagnostics = {
    Error = ' ',
    Warn = ' ',
    Hint = ' ',
    Info = ' ',
  },
  kinds = {
    Array = '󰅪',
    Branch = '',
    Boolean = '◩',
    Class = '󰠱',
    Color = '󰏘',
    Constant = '󰏿',
    Constructor = '',
    Enum = '',
    EnumMember = '',
    Event = '',
    Field = '󰆨',
    File = '󰈙',
    Folder = '󰉋',
    Function = 'ƒ',
    Interface = '',
    Key = '',
    Keyword = '󰌋',
    Method = '󰆧',
    Module = '󰏗 ',
    Namespace = '󰅩',
    Number = '󰎠',
    Null = '󰟢',
    Object = '⦿',
    Operator = '+',
    Package = '󰏗',
    Property = '󰜢',
    Reference = '',
    Snippet = '',
    String = '𝓐',
    Struct = '',
    Text = '',
    TypeParameter = '󰆩',
    Unit = '',
    Value = '󰎠',
    Variable = '󰀫',
  },
  cmp_sources = {
    nvim_lsp = '✨',
    luasnip = '🚀',
    buffer = '📝',
    path = '📁',
    cmdline = '💻',
  },
}
