#!/opt/homebrew/bin/bash

source "$CONFIG_DIR/colors.sh"

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####
sketchybar --bar position=top height=32 \
                 color=$BAR_COLOR \
                 padding_left=10 \
                 padding_right=10


##### Changing Defaults #####
default=(
	icon.font="BlexMono Nerd Font:Regular:13.0"
	icon.color=$TEXT_COLOR
	label.font="BlexMono Nerd Font:Regular:13.0"
	label.color=$TEXT_COLOR
	padding_left=5
	padding_right=5
	background.color=$ITEM_BG_COLOR
)
sketchybar --default "${default[@]}"

##### Adding items #####
sketchybar --add event aerospace_workspace_change
sketchybar --add event theme_change "AppleInterfaceThemeChangedNotification"
sketchybar --add item theme_listener left \
           --set theme_listener script="$PLUGIN_DIR/theme_change.sh" \
                                drawing=off \
           --subscribe theme_listener theme_change

source "$ITEM_DIR/workspace.sh"
source "$ITEM_DIR/front_app.sh"
source "$ITEM_DIR/clock.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/spotify.sh"

##### Force all scripts to run the first time #####
sketchybar --update
