#!/usr/bin/env sh

source "$HOME/.config/sketchybar/colors.sh"

PLUGIN_DIR="$HOME/.config/sketchybar/controller"
ITEM_DIR="$HOME/.config/sketchybar/view"

PADDING=4
PADDING_LABEL=4
LABEL="JetBrainsMono Nerd Font"

sketchybar --bar     height=27                                            \
                     blur_radius=0                                        \
                     padding_left=4                                       \
                     padding_right=4                                      \
                     color=0xff000000                                   \
                     position=top                                      \
                     sticky=on                                            \
                     font_smoothing=on                                    \
                                                                          \
           --default updates=when_shown                                   \
                     drawing=on                                           \
                     icon.font="$LABEL:Bold:13"                      \
                     label.font="$LABEL:Bold:13"                    \
                     icon.padding_left=$PADDING                           \
                     icon.padding_right=2                          \
                     label.padding_left=$PADDING_LABEL                          \
                     label.padding_right=$PADDING_LABEL                         \
                     label.color=0xff${NORD4:1}                           \
                     icon.color=0xff${NORD4:1}                            \


# left
source "$ITEM_DIR/space.sh"
source "$ITEM_DIR/front_app.sh"
# source "$ITEM_DIR/space_index.sh"
# source "$ITEM_DIR/team.sh"

# right
source "$ITEM_DIR/time.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/keyboard.sh"
# source "$ITEM_DIR/airpodsbattery.sh"
# source "$ITEM_DIR/disk.sh"
source "$ITEM_DIR/mem.sh"
source "$ITEM_DIR/cpu.sh"
source "$ITEM_DIR/wifi.sh"
source "$ITEM_DIR/docker.sh"
source "$ITEM_DIR/vpn.sh"
# source "$ITEM_DIR/task.sh"
# source "$ITEM_DIR/spotify.sh"
# source "$ITEM_DIR/github.sh"
# source "$ITEM_DIR/slack.sh"

# initializing
sketchybar --update

echo "sketchybar configuration loaded.."
