require "mappings"
require "options"

require "cores.git"
require "cores.sneak"

require "plugins.dashboard"
require "plugins.far"
require "plugins.fterm"
require "plugins.git_worktree"
require "plugins.neoscroll"
require "plugins.nrrwrgn"
require "plugins.range_highlight"
require "plugins.vim-test"
require "plugins.vimwiki"
require "plugins.wordmotion"
