require "cmds"
require "mappings"
require "options"

require "cores.git"
require "cores.sneak"

require "plugins.comment"
require "plugins.dashboard"
require "plugins.far"
require "plugins.fastfold"
require "plugins.fterm"
require "plugins.git_worktree"
require "plugins.notify"
require "plugins.nrrwrgn"
require "plugins.spector"
require "plugins.vim-test"
require "plugins.vimwiki"
require "plugins.vista"
require "plugins.wilder"
require "plugins.wordmotion"
