vim.g.mapleader = " "

require("mapping_config.anzu")
require("mapping_config.buffer")
require("mapping_config.compe")
require("mapping_config.dashboard")
require("mapping_config.fterm")
require("mapping_config.general")
require("mapping_config.git")
require("mapping_config.lsp")
require("mapping_config.mundo")
require("mapping_config.rest")
require("mapping_config.telescope")
require("mapping_config.tree")
require("mapping_config.truezen")
require("mapping_config.vimux")

require("mapping_config.editor.block")
require("mapping_config.editor.commenter")
require("mapping_config.editor.fold")
require("mapping_config.editor.markdown")
require("mapping_config.editor.prettier")
require("mapping_config.editor.wordmotion")
require("mapping_config.editor.nrrwrgn")

require("mapping_config.languages.rails")
