require("mappings.anzu")
require("mappings.buffer")
require("mappings.compe")
require("mappings.dashboard")
require("mappings.general")
require("mappings.git")
require("mappings.lsp")
require("mappings.mundo")
require("mappings.telescope")
require("mappings.tree")
require("mappings.truezen")
require("mappings.vimux")

require("mappings.editor.block")
require("mappings.editor.commenter")
require("mappings.editor.fold")
require("mappings.editor.markdown")
require("mappings.editor.prettier")
require("mappings.editor.wordmotion")

require("mappings.languages.rails")
