alias cat='bat'
alias nv="nvim"
alias c="clear"
alias rf='rm -rf'
alias sdn="osascript -e 'tell app \"System Events\" to shut down'"
alias ll="ls -l"
alias lla="ll -A"
alias z="j"
alias cdes="rm ~/Desktop/*"
