alias bdi='bundle install'
alias bdu='bundle update --bundler'
alias railst='bundle exec rspec'
alias railss='bundle exec rails s -p'
alias railsm='bundle exec rails db:migrate'
alias railsg='bundle exec rails generate'
